#!/usr/bin/env bash
# Configure doman zone so that the subdomain www points to load-balancer IP
domain_output () {
	line_output=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $line_output" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
	domain_output "$1" "www"
	domain_output "$1" "lb-01"
	domain_output "$1" "web-01"
	domain_output "$1" "web-02"
elif [ "$#" == 2 ]
then
	domain_output "$1" "$2"
fi
