#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo sed -i '/server.name..;/a \        error_page 404 /error.html;\n           location = /error.html {\n              root /var/www/html;\n           internal;\n     }'  /etc/nginx/sites-enabled/default
sudo service nginx restart
