#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html
sudo touch /var/www/html/index.html
sudo chmod 666 /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
sudo chmod 666 /etc/nginx/sites-enabled/default
sudo sed -i '/server_name _;/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo touch /var/www/html/error.html
sudo chmod 666 /var/www/html/error.html
sudo echo "Ceci n'est pas une page \n" > /var/www/html/error.html
sudo sed -i '/server_name _;/a \        error_page 404 /error.html;\n\tlocation = /error.html {\n               root /var/www/html;\n           internal;\n     }'  /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _;/a \        add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart
