#!/usr/bin/env bash
# Display To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# Display I am invincible!!! when receiving a SIGTERM signal
# shellcheck disable=SC2046
while :
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo I am invincible!!!" SIGTERM
done       
