#!/usr/bin/env bash
# Running nginx as nginx user
chmod 666 /etc/nginx/nginx.conf
chmod 666 /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
